// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZY_-upWd7c28t8C4yaGNgK615MwBcX4',
    appId: '1:235451228126:web:7639a082bed50fdeda074f',
    messagingSenderId: '235451228126',
    projectId: 'winbetarena-bcdb7',
    authDomain: 'winbetarena-bcdb7.firebaseapp.com',
    storageBucket: 'winbetarena-bcdb7.firebasestorage.app',
    measurementId: 'G-K1X79GX2QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiYHp3lsmZM0OVgHKQwln2C0w-6cR0rsE',
    appId: '1:235451228126:android:8243c88d013131c1da074f',
    messagingSenderId: '235451228126',
    projectId: 'winbetarena-bcdb7',
    storageBucket: 'winbetarena-bcdb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYcoT6raKxyLn_AMVBtJqB-XNWk514fo',
    appId: '1:235451228126:ios:1f5eff5664817ef6da074f',
    messagingSenderId: '235451228126',
    projectId: 'winbetarena-bcdb7',
    storageBucket: 'winbetarena-bcdb7.firebasestorage.app',
    iosBundleId: 'com.example.winbetArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvYcoT6raKxyLn_AMVBtJqB-XNWk514fo',
    appId: '1:235451228126:ios:1f5eff5664817ef6da074f',
    messagingSenderId: '235451228126',
    projectId: 'winbetarena-bcdb7',
    storageBucket: 'winbetarena-bcdb7.firebasestorage.app',
    iosBundleId: 'com.example.winbetArena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIZY_-upWd7c28t8C4yaGNgK615MwBcX4',
    appId: '1:235451228126:web:9ccb17a07c88ebb7da074f',
    messagingSenderId: '235451228126',
    projectId: 'winbetarena-bcdb7',
    authDomain: 'winbetarena-bcdb7.firebaseapp.com',
    storageBucket: 'winbetarena-bcdb7.firebasestorage.app',
    measurementId: 'G-ER3T68R08T',
  );
}
